name: Deploy React app on EC2

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Deploy to EC2 using SSM
        id: deploy_ssm
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --comment "Deploy React app" \
            --parameters commands='
              git config --global --add safe.directory /home/ubuntu/downloads/deploy-next-docker-aws-ec2 &&
              cd /home/ubuntu/downloads/deploy-next-docker-aws-ec2 &&
              git fetch origin &&
              git checkout production &&
              git reset --hard origin/production &&
              docker build -t blog-starter . &&
              docker rm -f blog-starter-container || true &&
              docker run -d --name blog-starter-container -p 80:3000 blog-starter
            ' \
            --region ${{ secrets.REGION }} \
            --query "Command.CommandId" --output text)

          echo "Run COMMAND_ID=$COMMAND_ID"

          for i in {1..10}; do
            STATUS=$(aws ssm list-command-invocations --command-id $COMMAND_ID --details --query "CommandInvocations[0].Status" --output text)
            echo "Attempt $i: Status = $STATUS"
            if [[ "$STATUS" == "Success" ]]; then
              echo "Command succeeded"
              exit 0
            elif [[ "$STATUS" == "Failed" || "$STATUS" == "Cancelled" || "$STATUS" == "TimedOut" ]]; then
              echo "Command failed with status $STATUS"
              exit 1
            fi
            sleep 10
          done

          echo "Command did not complete in time"
          exit 1
