name: Check UT before merging

on:
  pull_request:
    branches: [ "production" ]

jobs:
  building:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #   tạm bỏ cache: 'npm' vì không có package-lock.json
    - run: npm install
    # nên dùng npm ci nhưng do có agencybloc nên không đẩy lên được
    - run: npm run build --if-present
    - run: npm test